//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STS.Resources.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shipments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shipments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STS.Resources.Scripts.Shipments", typeof(Shipments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector Name is Required.
        /// </summary>
        public static string CollectorNameRequired {
            get {
                return ResourceManager.GetString("CollectorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert The Name Of Shipment Collector.
        /// </summary>
        public static string InsertTheNameOfShipmentCollector {
            get {
                return ResourceManager.GetString("InsertTheNameOfShipmentCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Tracking Number Of Arrived Shipment.
        /// </summary>
        public static string InsertTrackingNumberOfArrivedShipment {
            get {
                return ResourceManager.GetString("InsertTrackingNumberOfArrivedShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver Name.
        /// </summary>
        public static string ReceiverName {
            get {
                return ResourceManager.GetString("ReceiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure That Shipment with Tracking Number _TrackingNumber_ Departed The Location ?.
        /// </summary>
        public static string ShipmentDepartedMessage {
            get {
                return ResourceManager.GetString("ShipmentDepartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number : _TrackingNumber_&lt;br&gt;Receiver Name : _ReceiverName_&lt;br&gt;Desitnation : _Destination_.
        /// </summary>
        public static string ShipmentPreviewMessage {
            get {
                return ResourceManager.GetString("ShipmentPreviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Shipments.
        /// </summary>
        public static string ShipmentsEmptyTable {
            get {
                return ResourceManager.GetString("ShipmentsEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected.
        /// </summary>
        public static string ShipmentsTableCollectedLabel {
            get {
                return ResourceManager.GetString("ShipmentsTableCollectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departed.
        /// </summary>
        public static string ShipmentsTableDepartedLabel {
            get {
                return ResourceManager.GetString("ShipmentsTableDepartedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ShipmentsTableDetailsLabel {
            get {
                return ResourceManager.GetString("ShipmentsTableDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string ShipmentsTableFirst {
            get {
                return ResourceManager.GetString("ShipmentsTableFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string ShipmentsTableLast {
            get {
                return ResourceManager.GetString("ShipmentsTableLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string ShipmentsTableLengthMenu {
            get {
                return ResourceManager.GetString("ShipmentsTableLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string ShipmentsTableLoadingRecords {
            get {
                return ResourceManager.GetString("ShipmentsTableLoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ShipmentsTableNext {
            get {
                return ResourceManager.GetString("ShipmentsTableNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string ShipmentsTableOperationsMenuDirection {
            get {
                return ResourceManager.GetString("ShipmentsTableOperationsMenuDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ShipmentsTablePrevious {
            get {
                return ResourceManager.GetString("ShipmentsTablePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string ShipmentsTableProcessing {
            get {
                return ResourceManager.GetString("ShipmentsTableProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search :.
        /// </summary>
        public static string ShipmentsTableSearchLabel {
            get {
                return ResourceManager.GetString("ShipmentsTableSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string ShipmentsTableSendSMSLabel {
            get {
                return ResourceManager.GetString("ShipmentsTableSendSMSLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information.
        /// </summary>
        public static string ShipmentsTableUpdateInformationLabel {
            get {
                return ResourceManager.GetString("ShipmentsTableUpdateInformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string ShipmentTableInfo {
            get {
                return ResourceManager.GetString("ShipmentTableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number.
        /// </summary>
        public static string TrackingNumber {
            get {
                return ResourceManager.GetString("TrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Number Not Found.
        /// </summary>
        public static string TrackingNumberNotFound {
            get {
                return ResourceManager.GetString("TrackingNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No Tracking Number was Inserted.
        /// </summary>
        public static string TrackingNumberRequired {
            get {
                return ResourceManager.GetString("TrackingNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Shipping.
        /// </summary>
        public static string WaitingShipping {
            get {
                return ResourceManager.GetString("WaitingShipping", resourceCulture);
            }
        }
    }
}
